version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/app
      - node_modules:/workspaces/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Use shell form to ensure proper signal handling
      - CHOKIDAR_USEPOLLING=true
    command: /bin/sh -c "npm install && npm run dev"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    # Ensure container doesn't stop immediately
    tty: true
    stdin_open: true

volumes:
  node_modules:
